### PR TITLE
Prioritise using provided socket factory when creating socket with proxy

### LINKED ISSUE #1058: How to debugg the client using Fiddler or sth else
**Describe what you would like to know or do**
I'd like to debug my websocket client using Fiddler

**Describe the solution you'd considered**
I've tried `proxy` like [this](https://github.com/TooTallNate/Java-WebSocket/blob/65300d44507e5a4ed942b92dd27873cb8b95c936/src/main/example/ProxyClientExample.java), but it reports cert error.
```
ExampleClient c = new ExampleClient(new URI("wss://a-site-to-test.com:12345"));
c.setProxy(new Proxy(Proxy.Type.HTTP, new InetSocketAddress("127.0.0.1", 8888)));
c.connect();
```

I googled that and copied a factory to trust all certs. The client works, but the https stream didn't goto Fiddler
```
ExampleClient c = new ExampleClient(new URI("wss://a-site-to-test.com:12345"));
c.setProxy(new Proxy(Proxy.Type.HTTP, new InetSocketAddress("127.0.0.1", 8888)));
c.setSocketFactory(TrustAllCertSSLUtil.getFactory());
c.connect();
```

**Additional context**
**TrustAllCertSSLUtil.java**
```
public class TrustAllCertSSLUtil implements TrustManager, X509TrustManager {

	private TrustAllCertSSLUtil() {
	}

	private static SSLSocketFactory sslFactory = null;

	public static SSLSocketFactory getFactory() throws Exception {
		if (sslFactory == null) {
			TrustManager[] trustAllCerts = new TrustManager[1];
			TrustManager tm = new TrustAllCertSSLUtil();
			trustAllCerts[0] = tm;
			SSLContext sc = SSLContext.getInstance("SSL");
			sc.init(null, trustAllCerts, null);
			sslFactory = sc.getSocketFactory();
		}
		return sslFactory;
	}

	public java.security.cert.X509Certificate[] getAcceptedIssuers() {
		return null;
	}

	public boolean isServerTrusted(java.security.cert.X509Certificate[] certs) {
		return true;
	}

	public boolean isClientTrusted(java.security.cert.X509Certificate[] certs) {
		return true;
	}

	public void checkServerTrusted(java.security.cert.X509Certificate[] certs, String authType)
			throws java.security.cert.CertificateException {
		return;
	}

	public void checkClientTrusted(java.security.cert.X509Certificate[] certs, String authType)
			throws java.security.cert.CertificateException {
		return;
	}
}
```

### PR DESCRIPTION
**Pull request by marci4**
## Description

Use the provided socket factory over a newly created one when creating a socket with a proxy

## Related Issue

Fixes #1058

## Motivation and Context

Bug fix

## How Has This Been Tested?

Manual test. Contains NO automatic test

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

File: src/main/java/org/java_websocket/client/WebSocketClient.java [hunk 1]
```diff
@@ -480,10 +484,17 @@ public void run() {
       }
 
       // if the socket is set by others we don't apply any TLS wrapper
-      if (isNewSocket && "wss".equals(uri.getScheme())) {
-        SSLContext sslContext = SSLContext.getInstance("TLSv1.2");
-        sslContext.init(null, null, null);
-        SSLSocketFactory factory = sslContext.getSocketFactory();
+      if (upgradeSocketToSSLSocket && "wss".equals(uri.getScheme())) {
+        SSLSocketFactory factory = null;
```
Comment (PhilipRoman) [inline src/main/java/org/java_websocket/client/WebSocketClient.java:488]: I would remove the initialization with null to make the compiler check that factory is initialized in all code branches.

**Review by PhilipRoman — APPROVED** [review]
Looks good!
