### PR TITLE
Replace TimerTask with ScheduledExecutorService

### LINKED ISSUE #869: Lost connection detection is sensitive to changes in system time
Because Lost Connection Detection uses the `java.util.Timer` API [instead of the `ScheduledThreadPoolExecutor` API](https://stackoverflow.com/a/409993/4651874), it is sensitive to changes in the system time. For example, if you set the system time to a point years in the future, the `connectionLostTimerTask` will be called constantly, frequently causing disconnects as the clients cannot respond before the task is called again. This is particularly an issue for embedded devices that must have their clock set at runtime.

The best solution would seem to be to use the `ScheduledThreadPoolExecutor` API. I plan to submit a PR.

**To Reproduce**
1. Start a WebSocket server using this library
2. Set the system time to a few years in the future

### PR DESCRIPTION
**Pull request by NoahAndrews**
## Description
By getting rid of TimerTask, we remove an assumption that the system clock will not be modified.

## Related Issue
Fixes #869 

## How Has This Been Tested?
Observed that there is no longer an issue when the system time is changed.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed (aside from the ones that previously failed).

### CODE REVIEW

File: src/main/java/org/java_websocket/util/NamedThreadFactory.java [hunk 1]
```diff
@@ -0,0 +1,47 @@
+/*
```
Comment (marci4) [inline src/main/java/org/java_websocket/util/NamedThreadFactory.java]: Could you please use the license provided in https://github.com/TooTallNate/Java-WebSocket/blob/master/LICENSE

Comment (NoahAndrews) [reply src/main/java/org/java_websocket/util/NamedThreadFactory.java]: Done

**Comment by NoahAndrews** [comment]
Ready for re-review
