### PR TITLE
PermessageDeflate should handle uncompressed messages

### LINKED ISSUE #1164: [Android & Node.js Server] Problem using PerMessageDeflateExtension with custom ping/pong messages ?
Hi, I have a question about using `PerMessageDeflateExtension`.

```
E/SessionManager: ◖[Session] WebSocket error #Network	⚑[SessionManager$listenToEvents$6.accept:358]
E/SessionManager: ◖ org.java_websocket.exceptions.InvalidFrameException: RSV1 bit must be set for DataFrames.
E/SessionManager: ◖	at org.java_websocket.extensions.permessage_deflate.PerMessageDeflateExtension.isFrameValid(PerMessageDeflateExtension.java:321)
E/SessionManager: ◖	at org.java_websocket.drafts.Draft_6455.translateSingleFrame(Draft_6455.java:565)
E/SessionManager: ◖	at org.java_websocket.drafts.Draft_6455.translateFrame(Draft_6455.java:739)
E/SessionManager: ◖	at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:398)
E/SessionManager: ◖	at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:233)
E/SessionManager: ◖	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:516)
E/SessionManager: ◖	at java.lang.Thread.run(Thread.java:923)
E/SessionManager: ◖ 
```

I ran into above error log, so I made a break point like below. 

image

image

If you see the log, the payload contains our custom ping message which is being transferred in TextFrame. I would like to know if this kind of custom ping/pong message could interfere with using PerMessageDeflateExtensions properly. (I checked the RFC 6455 document and read that Ping/Pong Frames have different opcodes) 

Also, I couldn't understand the purpose of the below lines. 

```java
    public void isFrameValid(Framedata inputFrame) throws InvalidDataException {
        if((inputFrame instanceof TextFrame || inputFrame instanceof BinaryFrame) && !inputFrame.isRSV1())
            throw new InvalidFrameException("RSV1 bit must be set for DataFrames.");
```

Does this mean that all TextFrame & BinaryFrame data should have isRSV1() set to true ? If so, how does it handle situations when server compresses data selectively? 

Best Regards, 
Sara. 

---

* Java-WebSocket Version 1.5.2
* Java 1.8 
* Node.js uses ws websocket library

### PR DESCRIPTION
**Pull request by marci4**
## Description

PerMessageDeflate messages may be uncompressed and should therefore not fail

## Related Issue

Fixes #1164

## Motivation and Context

Bugfix

## How Has This Been Tested?

Manual test was not possible since the reporter did not include an example application

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

File: src/main/java/org/java_websocket/extensions/permessage_deflate/PerMessageDeflateExtension.java [hunk 1]
```diff
@@ -190,12 +214,16 @@ public void encodeFrame(Framedata inputFrame) {
...
+    if (payloadData.length < threshold) {
+      return;
+    }
     // Only the first frame's RSV1 must be set.
     if (!(inputFrame instanceof ContinuousFrame)) {
       ((DataFrame) inputFrame).setRSV1(true);
     }
 
-    deflater.setInput(inputFrame.getPayloadData().array());
+    deflater.setInput(payloadData);
```
Comment (PhilipRoman) [inline src/main/java/org/java_websocket/extensions/permessage_deflate/PerMessageDeflateExtension.java:226]: You can simplify this by using the ByteBuffer directly (setInput has an overload for it) and `remaining()` instead of `array().length` above

**Review by PhilipRoman — APPROVED** [review]
Looks good!

**Comment by SaraHan774** [comment]
Hi, Thanks for the fix! 

By the way, what exactly did you mean by example application? This is my first time reporting an issue in open source repository and I think I misunderstood what you meant by 'example application'. Are there any links that I can refer to? 

Best Regards, 
Sara.

**Comment by PhilipRoman** [comment]
@SaraHan774 "Example application" means a (small) program using this library that makes the issue visible. This saves time for developers, because they don't have to spend time trying to reproduce the bug and can just run the provided application to see the issue.

**Comment by SaraHan774** [comment]
Thank you for the answer. I will keep that in mind next time!
