### PR TITLE
Issue-1160 Added java.lang.Error handling in WebSocketImpl and WebSocketServer

### LINKED ISSUE #1160: `WebSocketWorker` does not handle `Throwable`
**Describe the bug**
The `WebSocketWorker` does not catch thrown (non-`Exception`) `Throwable`s; instead they cause the worker thread to die. Even though in general catching `Throwable` should be avoided it seems appropriate here, otherwise an adversary could exploit a vulnerability in the application, killing one worker thread after the other until no more workers are remaining, causing a denial of service.

Even though [`java.lang.Error`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Error.html) is described as:
> An Error is a subclass of Throwable that indicates serious problems that a reasonable application should not try to catch.

Some of the subclasses are thrown for non-serious problems, e.g. `StackOverflowError` could occur when malicious deeply nested data is deserialized.

**To Reproduce**
1. Modify the `onMessage(WebSocket, String)` method of the [example `ChatServer`](https://github.com/TooTallNate/Java-WebSocket/blob/master/src/main/example/ChatServer.java) to throw a `java.lang.Error` (simulating an error in the application code)
2. Start the server
3. Run the [`ExampleClient`](https://github.com/TooTallNate/Java-WebSocket/blob/master/src/main/example/ExampleClient.java) multiple times
:x: At some point all worker threads have died

**Expected behavior**
`WebSocketWorker` should catch `Throwable` and log it as fatal error, but it should not terminate due to it.

Alternatively shut down the complete server so whoever started it will notice that an error occurred (and can restart the server).

**Environment**
 - Version used: 1.5.3-SNAPSHOT (5f8d5979ae18a2741cf68d7f57fda562d783169c)

**Additional context**
It appears in previous versions the following `catch` block for `RuntimeException`s would have caused a complete server shutdown, see #207:
https://github.com/TooTallNate/Java-WebSocket/blob/5f8d5979ae18a2741cf68d7f57fda562d783169c/src/main/java/org/java_websocket/server/WebSocketServer.java#L1082-L1084
However, in current versions that `catch` block cannot be reached (except for bugs caused by this library) since the called method `doDecode` catches and logs any thrown `Exception`.

### PR DESCRIPTION
**Pull request by Serpion-ua**
Added java.lang.Error handling in WebSocketImpl and WebSocketServer. Fatal Error ( VirtualMachineError | ThreadDeath | LinkageError ) lead to stopping of WebSocketServer. Now non-fatal Error leads to closing of web socket but not stopping of WebSocketServer.

Fixes #1160

### CODE REVIEW

**Comment by Marcono1234** [comment]
When wrapping the `Error` in an `Exception` it might be good to preserve its stack trace, e.g. by using `new Exception(e)` instead of `new Exception(e.getMessage())`.

**Comment by Serpion-ua** [comment]
> When wrapping the `Error` in an `Exception` it might be good to preserve its stack trace, e.g. by using `new Exception(e)` instead of `new Exception(e.getMessage())`.

@Marcono1234 yeap, changed

File: src/main/java/org/java_websocket/server/WebSocketServer.java [hunk 1]
```diff
@@ -1079,8 +1079,20 @@ public void run() {
         }
       } catch (InterruptedException e) {
         Thread.currentThread().interrupt();
-      } catch (RuntimeException e) {
-        handleFatal(ws, e);
+      } catch (VirtualMachineError | ThreadDeath | LinkageError e) {
+        if (ws != null) {
+          ws.close();
+        }
+        log.error("Got fatal error in worker thread" + getName());
```
Comment (PhilipRoman) [inline src/main/java/org/java_websocket/server/WebSocketServer.java:1086]: This could use logger parameter `{}` instead of string concat

File: src/main/java/org/java_websocket/WebSocketImpl.java [hunk 2]
```diff
@@ -410,6 +412,14 @@ private void decodeFrames(ByteBuffer socketBuffer) {
...
       wsl.onWebsocketError(this, e);
       close(e);
+    } catch (VirtualMachineError | ThreadDeath | LinkageError e) {
+      log.error("Got fatal error during frame processing");
+      throw e;
+    } catch (Error e) {
+      log.error("Closing web socket due to an error during frame processing");
+      Exception exception = new Exception(e);
+      wsl.onWebsocketError(this, exception);
+      close(CloseFrame.UNEXPECTED_CONDITION, exception.getMessage());
```
Comment (PhilipRoman) [inline src/main/java/org/java_websocket/WebSocketImpl.java:422]: I'm not sure if its a good idea to send exception message to the client. There are a lot of subclasses of Error which could leak important information. I've personally seen cases where data like string lengths, file paths and sql queries is leaked through exception messages.

File: src/main/java/org/java_websocket/WebSocketImpl.java [hunk 3]
```diff
@@ -26,6 +26,8 @@
 package org.java_websocket;
 
 import java.io.IOException;
+import java.io.PrintWriter;
+import java.io.StringWriter;
```
[the remark this answers is not in the document]
Comment (Serpion-ua) [reply src/main/java/org/java_websocket/WebSocketImpl.java]: Removed

File: src/main/java/org/java_websocket/server/WebSocketServer.java (hunk 1 above)
Comment (Serpion-ua) [reply src/main/java/org/java_websocket/server/WebSocketServer.java]: fixed

File: src/main/java/org/java_websocket/WebSocketImpl.java (hunk 2 above)
Comment (Serpion-ua) [reply src/main/java/org/java_websocket/WebSocketImpl.java]: @PhilipRoman yeap good hint, changed to just return type of error without any additional information

Comment (PhilipRoman) [reply src/main/java/org/java_websocket/WebSocketImpl.java]: @Serpion-ua Looks good!
One last thing, the new error message mentions "server side", but WebSocketImpl is used for both server and client so you should probably remove that part.

Comment (Serpion-ua) [reply src/main/java/org/java_websocket/WebSocketImpl.java]: @PhilipRoman yeah removed that part.

**Review by PhilipRoman — APPROVED** [review]

**Comment by marci4** [comment]
@Serpion-ua thank you very much for your contribution!

@PhilipRoman thank you for your review!
